import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ClientWorkoutProvider from "@/context/ClientWorkoutProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning 
    >
     <body className="min-h-full flex flex-col bg-[#0b0d0f] text-white">
        <ClientWorkoutProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer
          position="top-right" 
          autoClose={3000} 
          theme="dark" 
        />
        </ClientWorkoutProvider>
      </body>
    </html>
  );
}
